-- ========================================
-- Code Camp Academy - Supabase Database Schema
-- ========================================
-- Created: 2026-01-05
-- Purpose: Complete database schema for Code Camp Academy project
-- ========================================

-- ========================================
-- Table 1: Codecamp (Challenges/Problems)
-- ========================================
CREATE TABLE IF NOT EXISTS public."Codecamp" (
    -- Primary Key
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- Challenge Information
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    difficulty INTEGER DEFAULT 5 CHECK (difficulty >= 1 AND difficulty <= 10),
    likes INTEGER DEFAULT 0,
    
    -- Code Configuration
    language TEXT NOT NULL DEFAULT 'javascript',
    initial_code TEXT,
    expected_output TEXT,
    
    -- Web Development (HTML/CSS/JS)
    initial_html TEXT,
    initial_css TEXT,
    initial_js TEXT,
    
    -- Validation Configuration
    validation_mode TEXT DEFAULT 'output_only' CHECK (
        validation_mode IN ('output_only', 'syntax_check', 'function_test')
    ),
    validation_script TEXT,
    
    -- Syntax Validation
    required_keywords JSONB DEFAULT '[]'::jsonb,
    forbidden_keywords JSONB DEFAULT '[]'::jsonb,
    
    -- Protected Code Ranges
    protected_ranges JSONB DEFAULT '[]'::jsonb,
    
    -- Test Cases
    test_cases JSONB DEFAULT '[]'::jsonb,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- Table 2: submiss (User Submissions)
-- ========================================
CREATE TABLE IF NOT EXISTS public."submiss" (
    -- Primary Key (same as challenge ID)
    id BIGINT PRIMARY KEY,
    
    -- User's Answer
    "ans-user" TEXT,
    
    -- Metadata
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Foreign Key
    CONSTRAINT fk_challenge
        FOREIGN KEY (id) 
        REFERENCES public."Codecamp"(id)
        ON DELETE CASCADE
);

-- ========================================
-- Indexes for Performance
-- ========================================

-- Index for Codecamp table
CREATE INDEX IF NOT EXISTS idx_codecamp_language ON public."Codecamp"(language);
CREATE INDEX IF NOT EXISTS idx_codecamp_difficulty ON public."Codecamp"(difficulty);
CREATE INDEX IF NOT EXISTS idx_codecamp_validation_mode ON public."Codecamp"(validation_mode);

-- Index for submiss table
CREATE INDEX IF NOT EXISTS idx_submiss_submitted_at ON public."submiss"(submitted_at);

-- ========================================
-- Row Level Security (RLS)
-- ========================================

-- Enable RLS
ALTER TABLE public."Codecamp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."submiss" ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access to Codecamp
CREATE POLICY "Allow public read access to Codecamp"
    ON public."Codecamp"
    FOR SELECT
    USING (true);

-- Policy: Allow public write access to Codecamp (for development)
CREATE POLICY "Allow public write access to Codecamp"
    ON public."Codecamp"
    FOR ALL
    USING (true);

-- Policy: Allow public read access to submiss
CREATE POLICY "Allow public read access to submiss"
    ON public."submiss"
    FOR SELECT
    USING (true);

-- Policy: Allow public write access to submiss
CREATE POLICY "Allow public write access to submiss"
    ON public."submiss"
    FOR ALL
    USING (true);

-- ========================================
-- Functions and Triggers
-- ========================================

-- Function: Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Auto-update updated_at for Codecamp
CREATE TRIGGER update_codecamp_updated_at
    BEFORE UPDATE ON public."Codecamp"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger: Auto-update updated_at for submiss
CREATE TRIGGER update_submiss_updated_at
    BEFORE UPDATE ON public."submiss"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ========================================
-- Sample Data (Optional)
-- ========================================

-- Sample Challenge 1: Hello World (JavaScript)
INSERT INTO public."Codecamp" (
    id,
    title,
    description,
    difficulty,
    likes,
    language,
    initial_code,
    expected_output,
    validation_mode
) VALUES (
    1,
    'Hello World',
    'เขียนโปรแกรมที่แสดงข้อความ "Hello World" ออกมา',
    1,
    127,
    'javascript',
    'console.log("Hello World");',
    'Hello World',
    'output_only'
) ON CONFLICT (id) DO NOTHING;

-- Sample Challenge 2: Function Test (JavaScript)
INSERT INTO public."Codecamp" (
    id,
    title,
    description,
    difficulty,
    likes,
    language,
    initial_code,
    validation_mode,
    validation_script
) VALUES (
    2,
    'Function: Add Two Numbers',
    'สร้างฟังก์ชัน add(a, b) ที่รับตัวเลข 2 ตัว และคืนค่าผลบวก',
    2,
    95,
    'javascript',
    'function add(a, b) {
  // เขียนโค้ดที่นี่
}',
    'function_test',
    '// Test Cases
const results = [];

// Test 1
try {
  const result1 = add(1, 2);
  results.push({ test: "add(1, 2)", expected: 3, actual: result1, passed: result1 === 3 });
} catch (e) {
  results.push({ test: "add(1, 2)", expected: 3, actual: "Error", passed: false });
}

// Test 2
try {
  const result2 = add(5, 7);
  results.push({ test: "add(5, 7)", expected: 12, actual: result2, passed: result2 === 12 });
} catch (e) {
  results.push({ test: "add(5, 7)", expected: 12, actual: "Error", passed: false });
}

// Test 3
try {
  const result3 = add(-3, 3);
  results.push({ test: "add(-3, 3)", expected: 0, actual: result3, passed: result3 === 0 });
} catch (e) {
  results.push({ test: "add(-3, 3)", expected: 0, actual: "Error", passed: false });
}

console.log(JSON.stringify(results));'
) ON CONFLICT (id) DO NOTHING;

-- Sample Challenge 3: Python Hello World
INSERT INTO public."Codecamp" (
    id,
    title,
    description,
    difficulty,
    likes,
    language,
    initial_code,
    expected_output,
    validation_mode
) VALUES (
    3,
    'Python: Hello World',
    'เขียนโปรแกรม Python ที่แสดงข้อความ "Hello Python" ออกมา',
    1,
    85,
    'python',
    'print("Hello Python")',
    'Hello Python',
    'output_only'
) ON CONFLICT (id) DO NOTHING;

-- Sample Challenge 4: Java Hello World
INSERT INTO public."Codecamp" (
    id,
    title,
    description,
    difficulty,
    likes,
    language,
    initial_code,
    expected_output,
    validation_mode
) VALUES (
    4,
    'Java: Hello World',
    'เขียนโปรแกรม Java ที่แสดงข้อความ "Hello Java" ออกมา',
    2,
    72,
    'java',
    'public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Java");
    }
}',
    'Hello Java',
    'output_only'
) ON CONFLICT (id) DO NOTHING;

-- Sample Challenge 5: Syntax Check Mode
INSERT INTO public."Codecamp" (
    id,
    title,
    description,
    difficulty,
    likes,
    language,
    initial_code,
    expected_output,
    validation_mode,
    required_keywords,
    forbidden_keywords
) VALUES (
    5,
    'JavaScript: If-Else Statement',
    'เขียนโปรแกรมที่ใช้ if-else statement เพื่อตรวจสอบว่าตัวเลขเป็นบวกหรือลบ',
    3,
    64,
    'javascript',
    'const number = 5;

// เขียนโค้ดที่นี่',
    'Positive',
    'syntax_check',
    '["if", "else"]',
    '["ternary"]'
) ON CONFLICT (id) DO NOTHING;

-- ========================================
-- Views (Optional - for analytics)
-- ========================================

-- View: Challenge Statistics
CREATE OR REPLACE VIEW challenge_stats AS
SELECT 
    c.id,
    c.title,
    c.language,
    c.difficulty,
    c.validation_mode,
    c.likes,
    COUNT(s.id) as submission_count,
    c.created_at
FROM public."Codecamp" c
LEFT JOIN public."submiss" s ON c.id = s.id
GROUP BY c.id, c.title, c.language, c.difficulty, c.validation_mode, c.likes, c.created_at
ORDER BY c.id;

-- ========================================
-- Comments
-- ========================================

COMMENT ON TABLE public."Codecamp" IS 'Stores all coding challenges/problems';
COMMENT ON TABLE public."submiss" IS 'Stores user submissions for each challenge';

COMMENT ON COLUMN public."Codecamp".validation_mode IS 'Validation mode: output_only, syntax_check, or function_test';
COMMENT ON COLUMN public."Codecamp".validation_script IS 'JavaScript code for function_test mode (test cases)';
COMMENT ON COLUMN public."Codecamp".protected_ranges IS 'JSON array of protected code ranges that users cannot edit';
COMMENT ON COLUMN public."Codecamp".test_cases IS 'JSON array of test cases with input/output pairs';

-- ========================================
-- Grant Permissions
-- ========================================

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- Grant permissions on tables
GRANT ALL ON public."Codecamp" TO anon, authenticated;
GRANT ALL ON public."submiss" TO anon, authenticated;

-- Grant permissions on sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ========================================
-- End of Schema
-- ========================================
